# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

# 해당 workflow가 언제 실행될건지 트리거 지정(Event Trigger)
# master branch에 push or pull request가 발생할 경우 동작함
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    #실행 환경 지정
    runs-on: ubuntu-latest
    
    # Task의 sequance 명시함
    steps:
    - name: Set up MySQL
      uses: samin/mysql-action@v1
      with:
        container port: 3306
        character set server: 'utf8'
        mysql database: 'svtcafe'
        mysql user: 'root'
        mysql password: ${{ secrets.MYSQL_PASSWORD }}
        
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
